"""
    $TYPEDEF

Simple wrapper struct for deprecated `update_A!`, `update_b!` API of `SymbolicLinearInterface`.
"""
struct UpdateABWrapper{A, B} <: Function
    update_A!::A
    update_b!::B
end

function (up::UpdateABWrapper)(A::AbstractMatrix, b::AbstractVector, p)
    up.update_A!(A, p)
    up.update_b!(b, p)
    return (A, b)
end

function (up::UpdateABWrapper)(p)
    A = up.update_A!(p)
    b = up.update_b!(p)
    return (A, b)
end

"""
    $(TYPEDEF)

A utility struct stored inside `LinearProblem` to enable a symbolic interface. Intended for
use by ModelingToolkit.jl.

# Fields

$(TYPEDFIELDS)
"""
@kwdef struct SymbolicLinearInterface{F, S, O, M}
    # the docstrings cannot start with a newline because otherwise the docs
    # builder fragments the list of fields into single-item lists (in TYPEDFIELDS)
    """A function which takes `A`, `b` and the parameter object `p` and updates both `A`
    and `b` in-place. For immutable `A` or `b`, this should only take `p` and return the
    new `(A, b)`. Previously, this API used `update_A!` and `update_b!` as separate functions
    with a similar contract. Supplying these individually is supported, but deprecated."""
    update_Ab::F
    """The symbolic backend for the `LinearProblem`."""
    sys::S
    """A function which when given a symbolic expression returns a function `(u, p)`
    that computes the expression."""
    observed::O
    """Arbitrary metadata useful for the symbolic backend."""
    metadata::M
end

# Separate `update_A!` and `update_b!` are deprecated in favor of a unified `update_Ab`.
function SymbolicLinearInterface(update_A!, update_b!, sys, observed, metadata)
    return SymbolicLinearInterface(;
        update_Ab = UpdateABWrapper(update_A!, update_b!), sys, observed, metadata
    )
end

@inline function Base.getproperty(sli::SymbolicLinearInterface, name::Symbol)
    if name === :update_A!
        return getfield(sli, :update_Ab).update_A!
    elseif name === :update_b!
        return getfield(sli, :update_Ab).update_b!
    else
        return getfield(sli, name)
    end
end

__has_sys(::SymbolicLinearInterface) = true
has_sys(::SymbolicLinearInterface) = true

SymbolicIndexingInterface.symbolic_container(sli::SymbolicLinearInterface) = sli.sys

function SymbolicIndexingInterface.observed(fn::SymbolicLinearInterface, sym)
    return if fn.observed !== nothing
        fn.observed(sym)
    elseif fn.sys !== nothing
        SymbolicIndexingInterface.observed(fn.sys, sym)
    else
        error("This `LinearProblem` does not support computing observed quantities.")
    end
end

@doc doc"""

Defines a linear system problem.
Documentation Page: <https://docs.sciml.ai/LinearSolve/stable/basics/LinearProblem/>

## Mathematical Specification of a Linear Problem

### Concrete `LinearProblem`

To define a `LinearProblem`, you simply need to give the `AbstractMatrix` ``A``
and an `AbstractVector` ``b`` which defines the linear system:

```math
Au = b
```

### Matrix-Free LinearProblem

For matrix-free versions, the specification of the problem is given by an
operator `A(u,p,t)` which computes `A*u`, or in-place as `A(du,u,p,t)`. These
are specified via the `AbstractSciMLOperator` interface. For more details, see
the [SciMLBase Documentation](https://docs.sciml.ai/SciMLBase/stable/).

Note that matrix-free versions of LinearProblem definitions are not compatible
with all solvers. To check a solver for compatibility, use the function `needs_concrete_A(alg::AbstractLinearAlgorithm)`.

## Problem Type

### Constructors

Optionally, an initial guess ``u₀`` can be supplied which is used for iterative
methods.

```julia
LinearProblem{isinplace}(A,b,p=NullParameters();u0=nothing,kwargs...)
LinearProblem(f::AbstractSciMLOperator,b,p=NullParameters();u0=nothing,kwargs...)
```

`isinplace` optionally sets whether the function is in-place or not, i.e. whether
the solvers are allowed to mutate. By default this is true for `AbstractMatrix`,
and for `AbstractSciMLOperator`s it matches the choice of the operator definition.

Parameters are optional, and if not given, then a `NullParameters()` singleton
will be used, which will throw nice errors if you try to index non-existent
parameters. Any extra keyword arguments are passed on to the solvers.

### Fields

* `A`: The representation of the linear operator.
* `b`: The right-hand side of the linear system.
* `p`: The parameters for the problem. Defaults to `NullParameters`. Currently unused.
* `u0`: The initial condition used by iterative solvers.
* `symbolic_interface`: An instance of `SymbolicLinearInterface` if the problem was
  generated by a symbolic backend.
* `kwargs`: The keyword arguments passed on to the solvers.
"""
struct LinearProblem{
        uType, isinplace, F, bType, P, I <: Union{SymbolicLinearInterface, Nothing}, K,
    } <:
    AbstractLinearProblem{bType, isinplace}
    A::F
    b::bType
    u0::uType
    p::P
    f::I
    kwargs::K
    @add_kwonly function LinearProblem{iip}(
            A, b, p = NullParameters(); u0 = nothing,
            f = nothing, kwargs...
        ) where {iip}
        warn_paramtype(p)
        new{typeof(u0), iip, typeof(A), typeof(b), typeof(p), typeof(f), typeof(kwargs)}(
            A, b, u0, p,
            f, kwargs
        )
    end
end

function LinearProblem(A, b, args...; kwargs...)
    return if A isa AbstractArray
        LinearProblem{true}(A, b, args...; kwargs...)
    elseif A isa Number
        LinearProblem{false}(A, b, args...; kwargs...)
    else
        LinearProblem{isinplace(A, 4)}(A, b, args...; kwargs...)
    end
end

SymbolicIndexingInterface.symbolic_container(prob::LinearProblem) = prob.f
SymbolicIndexingInterface.state_values(prob::LinearProblem) = prob.u0
SymbolicIndexingInterface.parameter_values(prob::LinearProblem) = prob.p
SymbolicIndexingInterface.is_time_dependent(::LinearProblem) = false
function SymbolicIndexingInterface.set_parameter!(
        valp::LinearProblem{A, B, C, D, E, <:SymbolicLinearInterface},
        val, idx
    ) where {A, B, C, D, E}
    set_parameter!(parameter_values(valp), val, idx)
    valp.f.update_Ab(valp.A, valp.b, valp.p)
    return nothing
end

@doc doc"""
    LinearAliasSpecifier{A, B}(; alias_A = nothing, alias_b = nothing, alias = nothing)

Holds information on what variables to alias
when solving a LinearProblem. Conforms to the AbstractAliasSpecifier interface. 

When a keyword argument is `nothing`, the default behaviour of the solver is used.

### Keywords

* `alias_A`: alias the `A` array.
* `alias_b`: alias the `b` array. 
* `alias`: sets all fields of the `LinearAliasSpecifier` to `alias`. 

Creates a `LinearAliasSpecifier` where `alias_A` and `alias_b` default to `nothing`.
When `alias_A` or `alias_b` is nothing, the default value of the solver is used.
"""
struct LinearAliasSpecifier{A, B} <: AbstractAliasSpecifier
    alias_A::A
    alias_b::B

    function LinearAliasSpecifier(; alias_A = nothing, alias_b = nothing, alias = nothing)
        return if alias == true
            new{Bool, Bool}(true, true)
        elseif alias == false
            new{Bool, Bool}(false, false)
        elseif isnothing(alias)
            new{typeof(alias_A), typeof(alias_b)}(alias_A, alias_b)
        end
    end
end
