# Put in a separate page so it can be used by SciMLDocs.jl

pages = [
    "Home" => "index.md",
    "Interfaces" => Any[
        "interfaces/Array_and_Number.md",
        "interfaces/Problems.md",
        "interfaces/Algebraic_Problem_Types.md",
        "interfaces/Differential_Equation_Problem_Types.md",
        "interfaces/Delay_Boundary_and_Noise_Problem_Types.md",
        "interfaces/Alias_Specifiers.md",
        "interfaces/Problem_Traits.md",
        "interfaces/SciMLFunctions.md",
        "interfaces/ODE_and_Discrete_Function_Types.md",
        "interfaces/Stochastic_Delay_and_DAE_Function_Types.md",
        "interfaces/Nonlinear_Optimization_and_Boundary_Function_Types.md",
        "interfaces/Algorithms.md",
        "interfaces/Solutions.md",
        "interfaces/Solution_Types.md",
        "interfaces/Symbolic_SaveIdxs.md",
        "interfaces/Callbacks.md",
        "interfaces/Clocks.md",
        "interfaces/Init_Solve.md",
        "interfaces/Ensembles.md",
        "interfaces/Common_Keywords.md",
        "interfaces/Differentiation.md",
        "interfaces/PDE.md",
    ],
    "Fundamentals" => Any["fundamentals/FAQ.md"],
]
