"""
IMPORTANT:

These types are used by the following packages, please notify with an issue if you need to
modify these structures:
- `SciML/MethodOfLines.jl`
"""

"""
$(TYPEDEF)

Solution to a PDE, solved from an ODEProblem generated by a discretizer.

`PDETimeSeriesSolution` is the concrete wrapper for time-dependent PDE
discretizations whose metadata subtypes
`AbstractDiscretizationMetadata{Val(true)}`. Discretizer packages usually define
an outer constructor `SciMLBase.PDETimeSeriesSolution(sol, metadata::D)` for
their metadata type `D`; the generic [`wrap_sol`](@ref SciMLBase.wrap_sol)
dispatch calls that constructor after the underlying ODE or time-dependent solve
has finished.

## Fields

  - `u`: the solution to the PDE, as a dictionary of symbols to Arrays of values. The
    Arrays are of the same shape as the domain of the PDE. Time is always the first axis.
  - `original_sol`: The original ODESolution that was used to generate this solution.
  - `t`: the time points corresponding to the saved values of the ODE solution.
  - `ivdomain`: The full list of domains for the independent variables. May be a grid for a
    discrete solution, or a vector/tuple of tuples for a continuous solution.
  - `ivs`: The list of independent variables for the solution.
  - `dvs`: The list of dependent variables for the solution.
  - `disc_data`: Metadata about the discretization process and type.
  - `prob`: The ODEProblem that was used to generate this solution.
  - `alg`: The algorithm used to solve the ODEProblem.
  - `interp`: Interpolations for the solution.
  - `retcode`: the return code from the solver. Used to determine whether the solver solved
    successfully, whether it terminated early due to a user-defined callback, or whether it
    exited due to an error. For more details, see
    [the return code documentation](https://docs.sciml.ai/SciMLBase/stable/interfaces/Solutions/#retcodes).
  - `stats`: statistics of the solver, such as the number of function evaluations required.
"""
struct PDETimeSeriesSolution{
        T, N, uType, Disc, Sol, DType, tType, domType, ivType, dvType,
        P, A,
        IType, S,
    } <: AbstractPDETimeSeriesSolution{T, N, uType, Disc}
    u::uType
    original_sol::Sol
    errors::DType
    t::tType
    ivdomain::domType
    ivs::ivType
    dvs::dvType
    disc_data::Disc
    prob::P
    alg::A
    interp::IType
    dense::Bool
    tslocation::Int
    retcode::ReturnCode.T
    stats::S
end

"""
Default callable fallback for time-series PDE wrappers.

Discretizer packages should implement this call interface for each supported
metadata type `D` when the wrapped PDE solution supports interpolation or
symbolic evaluation in the original PDE variables.
"""
function (sol::PDETimeSeriesSolution{T, N, S, D})(args...; kwargs...) where {T, N, S, D}
    error(ArgumentError("Call for PDETimeSeriesSolution not implemented for solution metadata type $D, please post an issue on the relevant discretizer package's github page."))
end

# Disambiguate with RecursiveArrayTools.AbstractDiffEqArray(t, ::Type{deriv}; idxs, continuity)
function (sol::PDETimeSeriesSolution{T, N, S, D})(
        t, ::Type{deriv}; idxs = nothing, continuity = :left
    ) where {T, N, S, D, deriv}
    error(ArgumentError("Call for PDETimeSeriesSolution not implemented for solution metadata type $D, please post an issue on the relevant discretizer package's github page."))
end

"""
$(TYPEDEF)

Solution to a PDE, solved from a NonlinearProblem generated by a discretizer.

`PDENoTimeSolution` is the concrete wrapper for time-independent PDE
discretizations whose metadata subtypes
`AbstractDiscretizationMetadata{Val(false)}`. Discretizer packages usually
define an outer constructor `SciMLBase.PDENoTimeSolution(sol, metadata::D)` for
their metadata type `D`; the generic [`wrap_sol`](@ref SciMLBase.wrap_sol)
dispatch calls that constructor after the underlying nonlinear, linear,
optimization, or stationary solve has finished.

## Fields

  - `u`: the solution to the PDE, as a dictionary of symbols to Arrays of values. The
    Arrays are of the same shape as the domain of the PDE. Time is always the first axis.
  - `original_sol`: The original NonlinearSolution that was used to generate this solution.
  - `ivdomain`: The full list of domains for the independent variables. May be a grid for a
    discrete solution, or a vector/tuple of tuples for a continuous solution.
  - `ivs`: The list of independent variables for the solution.
  - `dvs`: The list of dependent variables for the solution.
  - `disc_data`: Metadata about the discretization process and type.
  - `prob`: The NonlinearProblem that was used to generate this solution.
  - `alg`: The algorithm used to solve the NonlinearProblem.
  - `interp`: Interpolations for the solution.
  - `retcode`: The return code from the solver. Used to determine whether the solver solved
    successfully (`sol.retcode === ReturnCode.Success`), whether it terminated due to a user-defined
    callback (`sol.retcode === ReturnCode.Terminated`), or whether it exited due to an error. For more
    details, see the return code section of the ODEProblem.jl documentation.
"""
struct PDENoTimeSolution{
        T, N, uType, Disc, Sol, domType, ivType, dvType, P, A,
        IType, S,
    } <: AbstractPDENoTimeSolution{T, N, uType, Disc}
    u::uType
    original_sol::Sol
    ivdomain::domType
    ivs::ivType
    dvs::dvType
    disc_data::Disc
    prob::P
    alg::A
    interp::IType
    retcode::ReturnCode.T
    stats::S
end

const PDESolution{
    T, N, S, D,
} = Union{
    PDETimeSeriesSolution{T, N, S, D},
    PDENoTimeSolution{T, N, S, D},
}

"""
Default callable fallback for no-time PDE wrappers.

Discretizer packages should implement this call interface for each supported
metadata type `D` when the wrapped PDE solution supports evaluation in the
original PDE variables.
"""
function (sol::PDENoTimeSolution{T, N, S, D})(args...; kwargs...) where {T, N, S, D}
    error(ArgumentError("Call for PDENoTimeSolution not implemented for solution metadata type $D, please post an issue on the relevant discretizer package's github page."))
end

"""
    wrap_sol(sol, metadata::AbstractDiscretizationMetadata)

Wrap a solver solution produced by a PDE discretizer in the appropriate PDE
solution type.

Metadata with parameter `Val(true)` is routed to
`PDETimeSeriesSolution(sol, metadata)`. Metadata with parameter `Val(false)` is
routed to `PDENoTimeSolution(sol, metadata)`. Discretizer packages are
responsible for implementing those outer constructors for their concrete
metadata types and for filling the wrapper fields from the discretized solve.
"""
function SciMLBase.wrap_sol(
        sol,
        metadata::AbstractDiscretizationMetadata{hasTime}
    ) where {
        hasTime,
    }
    if hasTime isa Val{true}
        return PDETimeSeriesSolution(sol, metadata)
    else
        return PDENoTimeSolution(sol, metadata)
    end
end

"""
    pde_index_cotangent(config, sol::AbstractPDESolution, sym, Δ)

Reverse-mode hook behind `sol[sym]` and `sol[sym, inds...]` for a solution whose metadata
subtypes [`AbstractDifferentiableDiscretizationMetadata`](@ref SciMLBase.AbstractDifferentiableDiscretizationMetadata):
the cotangent of `sol.original_sol` for a cotangent `Δ` of the array `sol[sym]`, as a
`ChainRulesCore` tangent, or `NoTangent()` when `sym` does not depend on the solve (a
grid, for instance). The rules in the ChainRulesCore extension route every cotangent of a
wrapped solution back to `original_sol`, whose rules the solver packages provide; only the
map from a field back to the solver's solution is the discretizer's, and this is where it
implements it, for its metadata type `D`. `sym` is whatever the solution was indexed with,
and the metadata is a constant of the solve, with no cotangent. `config` is the rule
configuration, for `rrule_via_ad` on observed functions. The fallback errors, and a hook
that cannot provide a cotangent throws as well, so that a solution never returns a wrong
gradient silently.
"""
function pde_index_cotangent(
        config, sol::AbstractPDESolution{T, N, S, D}, sym, Δ
    ) where {T, N, S, D}
    throw(
        ArgumentError(
            "Reverse-mode differentiation of `sol[sym]` is not implemented for solution metadata type $D, please post an issue on the relevant discretizer package's github page."
        )
    )
end

"""
    pde_call_cotangent(config, sol::AbstractPDESolution, args, dv, Δ)

Reverse-mode hook behind `sol(args...; dv)`: a tuple `(Δsol, Δargs)` of the cotangent of
`sol.original_sol` and the cotangents of `args`, for a cotangent `Δ` of the evaluation at
`args`. `dv` is the keyword as it was passed to the call, or `nothing` when it was not, and
`Δ` then has the shape of what the call returns in that case (a collection over `sol.dvs`
in the documented interface). `Δargs` has one entry per argument: the cotangent of a
coordinate, or an error when the discretizer cannot provide it, and `NoTangent()` for an
index or a colon. See
[`pde_index_cotangent`](@ref SciMLBase.pde_index_cotangent) for the contract; the fallback
errors.
"""
function pde_call_cotangent(
        config, sol::AbstractPDESolution{T, N, S, D}, args, dv, Δ
    ) where {T, N, S, D}
    throw(
        ArgumentError(
            "Reverse-mode differentiation of `sol(args...)` is not implemented for solution metadata type $D, please post an issue on the relevant discretizer package's github page."
        )
    )
end

function Base.show(io::IO, m::MIME"text/plain", A::PDETimeSeriesSolution)
    println(io, string("retcode: ", A.retcode))
    println(io, string("Interpolation: "), typeof(A.interp))
    print(io, "t: ")
    show(io, m, A.t)
    print(io, "ivs: ")
    show(io, m, A.ivs)
    print(io, "domain:")
    show(io, m, A.ivdomain)
    println(io)
    print(io, "u: ")
    return show(io, m, A.u)
end

function Base.show(io::IO, m::MIME"text/plain", A::PDENoTimeSolution)
    println(io, string("retcode: ", A.retcode))
    println(io, string("Interpolation: "), typeof(A.interp))
    print(io, "ivs: ")
    show(io, m, A.ivs)
    print(io, "domain:")
    show(io, m, A.ivdomain)
    println(io)
    print(io, "u: ")
    return show(io, m, A.u)
end
