name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  downstream:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: DelayDiffEq.jl, group: Interface}
          - {user: SciML, repo: DelayDiffEq.jl, group: Integrators}
          - {user: SciML, repo: DelayDiffEq.jl, group: Regression}
          - {user: SciML, repo: DiffEqBase.jl, group: Core}
          - {user: SciML, repo: DiffEqDevTools.jl, group: Core}
          - {user: SciML, repo: DiffEqBase.jl, group: Downstream}
          - {user: SciML, repo: DiffEqBase.jl, group: Downstream2}
          - {user: SciML, repo: DiffEqFlux.jl, group: DiffEqFlux}
          - {user: SciML, repo: JumpProcesses.jl, group: All}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Interface}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Integrators}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Regression}
          - {user: SciML, repo: StochasticDiffEq.jl, group: Interface1}
          - {user: SciML, repo: StochasticDiffEq.jl, group: Interface2}
          - {user: SciML, repo: StochasticDiffEq.jl, group: Interface3}
          - {user: SciML, repo: StochasticDiffEq.jl, group: AlgConvergence}
          - {user: SciML, repo: Sundials.jl, group: All}
          - {user: SciML, repo: LinearSolve.jl, group: All}
          - {user: SciML, repo: NonlinearSolve.jl, group: Core}
          - {user: SciML, repo: Optimization.jl, group: All}
          - {user: SciML, repo: Integrals.jl, group: All}
          - {user: SciML, repo: BoundaryValueDiffEq.jl, group: All}
          - {user: SciML, repo: ModelingToolkit.jl, group: InterfaceI}
          - {user: SciML, repo: ModelingToolkit.jl, group: Initialization}
          - {user: SciML, repo: ModelingToolkit.jl, group: InterfaceII}
          - {user: SciML, repo: ModelingToolkit.jl, group: SymbolicIndexingInterface}
          - {user: SciML, repo: ModelingToolkit.jl, group: Extended}
          - {user: SciML, repo: ModelingToolkit.jl, group: Downstream}
          - {user: SciML, repo: ModelingToolkit.jl, group: FMI}
          - {user: SciML, repo: ModelingToolkit.jl, group: Extensions}
          - {user: SciML, repo: ModelingToolkitStandardLibrary.jl, group: Core}
          - {user: SciML, repo: SimpleDiffEq.jl, group: All}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core1}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core2}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core3}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core4}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core5}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core6}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core7}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core8}
          - {user: SciML, repo: Catalyst.jl, group: All}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
      julia-version: "1.10"
      julia-arch: "x64"
      julia-runtest-depwarn: "yes"
    secrets: "inherit"
